version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    depends_on:
      - obsidian
    volumes:
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ..:/var/www/docker
  obsidian:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: obsidian:dev
    environment:
      - USER=${USER}
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ..:/var/www/docker
      - ~/:/home/${USER}
  database:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./maria.d:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
