version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: obsidian_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - obsidian
    volumes:
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ..:/var/www/docker
  obsidian:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: obsidian:latest
    container_name: obsidian
    environment:
      - USER=${USER}
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ..:/var/www/docker
  database:
    image: mariadb
    container_name: obsidian_database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: obsidian
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: obsidian_phpmyadmin
    environment:
      - PMA_HOST=obsidian_database
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
