#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

GID=$(id -g)
export USER && export UID && export GID

usage() {
  echo "Usage: $0 {build|shell|root|up|down|clean|logs}"
}

build() {
  docker-compose -p obsidian build
}

shell() {
  up
  docker-compose -p obsidian exec -u $USER obsidian bash
}

root() {
  up
  docker-compose -p obsidian exec obsidian bash
}

up() {
  if [ ! -f ${DIR}/nginx/server.crt ]; then
    echo -n "Generating SSL cert... "
    ${DIR}/gencrt.sh > /dev/null
    echo "Done!"
  fi
  docker-compose -p obsidian up -d
}

down() {
  docker-compose -p obsidian stop
}

clean() {
  down
  docker-compose -p obsidian down -v
}

logs() {
  docker-compose -p obsidian logs -f
}

pushd "${DIR}" > /dev/null 2>&1
case $1 in
  build) build;;
  shell) shell;;
  root) root;;
  up) up;;
  down) down;;
  clean) clean;;
  logs) logs;;
  *) usage;;
esac
popd > /dev/null 2>&1
